FROM node:23 AS base
WORKDIR /usr/local/app

ARG DISCORD_APPLICATION_ID
ARG DISCORD_API_TOKEN
ARG OPENAI_API_KEY
ARG ELEVENLABS_XI_API_KEY
ARG GOOGLE_GENERATIVE_AI_API_KEY

# ELEVENLABS SETTINGS
ARG ELEVENLABS_MODEL_ID
ARG ELEVENLABS_VOICE_ID
ARG ELEVENLABS_VOICE_STABILITY
ARG ELEVENLABS_VOICE_SIMILARITY_BOOST
ARG ELEVENLABS_VOICE_STYLE
ARG ELEVENLABS_VOICE_USE_SPEAKER_BOOST
ARG ELEVENLABS_OPTIMIZE_STREAMING_LATENCY
ARG ELEVENLABS_OUTPUT_FORMAT

ARG TWITTER_DRY_RUN
ARG TWITTER_USERNAME
ARG TWITTER_PASSWORD
ARG TWITTER_EMAIL
ARG TWITTER_COOKIES

ARG X_SERVER_URL
ARG XAI_API_KEY
ARG XAI_MODEL

# For asking Claude stuff
ARG ANTHROPIC_API_KEY

ARG WALLET_PRIVATE_KEY
ARG WALLET_PUBLIC_KEY

ARG BIRDEYE_API_KEY

ARG SOL_ADDRESS
ARG SLIPPAGE
ARG RPC_URL
ARG HELIUS_API_KEY

## Telegram
ARG TELEGRAM_BOT_TOKEN
ARG TOGETHER_API_KEY

RUN apt-get update -qq && apt-get install ffmpeg -y && apt-get install docker.io -y

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack use pnpm@latest
COPY . .

## Possible Optimization from a pnpm doc to not include everything
#FROM base AS prod-deps
#RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile
# Need ts-node, which is dev dep?
#RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

#FROM base AS build
#RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
#RUN pnpm run build

#FROM base
#COPY --from=prod-deps /usr/local/app/node_modules /usr/local/app/node_modules
#COPY --from=build /usr/local/app/packages /usr/local/app/packages

# Non-optimized
RUN pnpm install --shamefully-hoist
RUN pnpm run build

ENV DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
ENV DISCORD_API_TOKEN=${DISCORD_API_TOKEN}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV ELEVENLABS_XI_API_KEY=${ELEVENLABS_XI_API_KEY}
ENV GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}

# ELEVENLABS SETTINGS
ENV ELEVENLABS_MODEL_ID=${ELEVENLABS_MODEL_ID}
ENV ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
ENV ELEVENLABS_VOICE_STABILITY=${ELEVENLABS_VOICE_STABILITY}
ENV ELEVENLABS_VOICE_SIMILARITY_BOOST=${ELEVENLABS_VOICE_SIMILARITY_BOOST}
ENV ELEVENLABS_VOICE_STYLE=${ELEVENLABS_VOICE_STYLE}
ENV ELEVENLABS_VOICE_USE_SPEAKER_BOOST=${ELEVENLABS_VOICE_USE_SPEAKER_BOOST}
ENV ELEVENLABS_OPTIMIZE_STREAMING_LATENCY=${ELEVENLABS_OPTIMIZE_STREAMING_LATENCY}
ENV ELEVENLABS_OUTPUT_FORMAT=${ELEVENLABS_OUTPUT_FORMAT}

ENV TWITTER_DRY_RUN=${TWITTER_DRY_RUN}
ENV TWITTER_USERNAME=${TWITTER_USERNAME}
ENV TWITTER_PASSWORD=${TWITTER_PASSWORD}
ENV TWITTER_EMAIL=${TWITTER_EMAIL}
ENV TWITTER_COOKIES=${TWITTER_COOKIES}

ENV X_SERVER_URL=${X_SERVER_URL}
ENV XAI_API_KEY=${XAI_API_KEY}
ENV XAI_MODEL=${XAI_MODEL}

# For asking Claude stuff
ENV ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

ENV WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
ENV WALLET_PUBLIC_KEY=${WALLET_PUBLIC_KEY}

ENV BIRDEYE_API_KEY=${BIRDEYE_API_KEY}

ENV SOL_ADDRESS=${SOL_ADDRESS}
ENV SLIPPAGE=${SLIPPAGE}
ENV RPC_URL=${RPC_URL}
ENV HELIUS_API_KEY=${HELIUS_API_KEY}

## Telegram
ENV TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ENV TOGETHER_API_KEY=${TOGETHER_API_KEY}

EXPOSE 3000
ENTRYPOINT pnpm start
